const SET_ANSWERS = 'SET_ANSWERS'
const SET_QUESTIONS = 'SET_QUESTIONS'
const SET_CONFIG_QUESTIONARY = 'SET_CONFIG_QUESTIONARY'
const SET_CURRENT_QUESTION_INDEX = 'SET_CURRENT_QUESTION_INDEX'
const SET_URL_FOR_IMAGE = 'SET_URL_FOR_IMAGE'
const UPDATE_CURRENT_ANSWER_CHOICE = 'UPDATE_CURRENT_ANSWER_CHOICE'

export default {
  SET_ANSWERS,
  SET_QUESTIONS,
  SET_CONFIG_QUESTIONARY,
  SET_CURRENT_QUESTION_INDEX,
  SET_URL_FOR_IMAGE,
  UPDATE_CURRENT_ANSWER_CHOICE
}
