const UPDATE_ANSWER = 'questionario/UPDATE_ANSWER'
const SET_ANSWERS = 'questionario/SET_ANSWERS'
const SET_REPETIR_QUESTOES = 'questionario/SET_REPETIR_QUESTOES'

export default { UPDATE_ANSWER, SET_ANSWERS, SET_REPETIR_QUESTOES }
